import { neon } from '@neondatabase/serverless';
export const MIRROR_BOARD_ID = 7829537690;
const MONDAY_RELAY = process.env.MONDAY_RELAY_URL || 'https://vybepainel-v2.vercel.app/api/monday';
let schemaPromise = null;
let reconcilePromise = null;
const MIRROR_RECONCILE_MIN_INTERVAL_MS = 60 * 1000;
const REMOVED_EVENT_TYPES = new Set(['item_deleted', 'delete_pulse', 'delete_item', 'item_archived', 'archive_pulse', 'archive_item']);
const RESTORED_EVENT_TYPES = new Set(['item_restored', 'restore_pulse', 'restore_item', 'unarchive_pulse']);

function database() { if (!process.env.DATABASE_URL) throw new Error('DATABASE_URL não configurada para o espelho operacional.'); return neon(process.env.DATABASE_URL); }
export async function ensureMirrorSchema() { if (!schemaPromise) { const sql = database(); schemaPromise = (async () => { await sql`CREATE TABLE IF NOT EXISTS vybe_mirror_items ( board_id BIGINT NOT NULL, item_id TEXT NOT NULL, raw JSONB NOT NULL, source_updated_at TEXT, deleted_at TIMESTAMPTZ, mirrored_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY (board_id, item_id) )`; await sql`CREATE INDEX IF NOT EXISTS vybe_mirror_items_board_active_idx ON vybe_mirror_items (board_id, mirrored_at DESC) WHERE deleted_at IS NULL`; await sql`CREATE TABLE IF NOT EXISTS vybe_mirror_changes ( change_id BIGSERIAL PRIMARY KEY, board_id BIGINT NOT NULL, item_id TEXT, operation TEXT NOT NULL, raw JSONB, source_updated_at TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW() )`; await sql`CREATE INDEX IF NOT EXISTS vybe_mirror_changes_board_idx ON vybe_mirror_changes (board_id, change_id DESC)`; await sql`CREATE TABLE IF NOT EXISTS vybe_mirror_events ( trigger_uuid TEXT PRIMARY KEY, board_id BIGINT NOT NULL, event_type TEXT, payload JSONB NOT NULL, received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), processed_at TIMESTAMPTZ, processing_error TEXT )`; await sql`CREATE TABLE IF NOT EXISTS vybe_mirror_meta ( meta_key TEXT PRIMARY KEY, meta_value JSONB NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW() )`; })().catch(error => { schemaPromise = null; throw error; }); } return schemaPromise; }
function json(value) { return JSON.stringify(value ?? null); }
export async function mondayQuery(query, variables = {}) { const response = await fetch(MONDAY_RELAY, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ query, variables }) }); const body = await response.json(); if (!response.ok || body?.errors?.length) throw new Error(body?.errors?.[0]?.message || body?.error || `Falha no relay Monday (${response.status})`); return body.data; }
export async function fetchAllMondayItems(onPage = null) { const all = []; let cursor = null; let page = 0; do { page += 1; const query = cursor ? `query($cursor: String!) { next_items_page(limit: 200, cursor: $cursor) { cursor items { id name updated_at group { id title } updates(limit: 3) { id body created_at creator { name } } column_values(ids:["lista_suspensa_mkmqnjbv","status","lista_suspensa0__1","person","data__1","data"]) { id text value ... on StatusValue { index label_style { color border } } } } } }` : `{ boards(ids:[${MIRROR_BOARD_ID}]) { items_page(limit: 200) { cursor items { id name updated_at group { id title } updates(limit: 3) { id body created_at creator { name } } column_values(ids:["lista_suspensa_mkmqnjbv","status","lista_suspensa0__1","person","data__1","data"]) { id text value ... on StatusValue { index label_style { color border } } } } } } }`; const data = await mondayQuery(query, cursor ? { cursor } : {}); const result = cursor ? data?.next_items_page : data?.boards?.[0]?.items_page; const items = result?.items || []; all.push(...items); if (onPage) onPage({ page, count: all.length }); cursor = result?.cursor || null; } while (cursor); return all; }
export async function fetchMondayStatusOptions() { const query = `{ boards(ids:[${MIRROR_BOARD_ID}]) { columns(ids:["status"]) { settings_str } } }`; const data = await mondayQuery(query); const raw = data?.boards?.[0]?.columns?.[0]?.settings_str || '{}'; const settings = JSON.parse(raw); const labels = settings.labels || {}; const colors = settings.labels_colors || {}; return Object.entries(labels).filter(([, label]) => label).map(([index, label]) => ({ index: Number(index), label, color: colors[index]?.color || '#c4c4c4', border: colors[index]?.border || colors[index]?.color || '#c4c4c4' })).sort((a, b) => a.index - b.index); }
export async function fetchMondayItem(itemId) { const query = `query($ids:[ID!]) { items(ids:$ids) { id name updated_at group { id title } updates(limit: 3) { id body created_at creator { name } } column_values(ids:["lista_suspensa_mkmqnjbv","status","lista_suspensa0__1","person","data__1","data"]) { id text value ... on StatusValue { index label_style { color border } } } } }`; const data = await mondayQuery(query, { ids: [String(itemId)] }); return data?.items?.[0] || null; }
async function latestVersion(sql, boardId = MIRROR_BOARD_ID) { const rows = await sql`SELECT COALESCE(MAX(change_id), 0)::bigint AS version FROM vybe_mirror_changes WHERE board_id=${boardId}`; return Number(rows[0]?.version || 0); }
async function setMeta(sql, key, value) { await sql`INSERT INTO vybe_mirror_meta (meta_key, meta_value, updated_at) VALUES (${key}, ${json(value)}::jsonb, NOW()) ON CONFLICT (meta_key) DO UPDATE SET meta_value=EXCLUDED.meta_value, updated_at=NOW()`; }
export async function bootstrapMirror() { await ensureMirrorSchema(); const [items, statusOptions] = await Promise.all([fetchAllMondayItems(), fetchMondayStatusOptions()]); const sql = database(); const rows = items.map(item => ({ item_id: String(item.id), raw: item, source_updated_at: item.updated_at || '' })); if (rows.length) { await sql`INSERT INTO vybe_mirror_items (board_id, item_id, raw, source_updated_at, deleted_at, mirrored_at) SELECT ${MIRROR_BOARD_ID}, record.item_id, record.raw, record.source_updated_at, NULL, NOW() FROM jsonb_to_recordset(${json(rows)}::jsonb) AS record(item_id text, raw jsonb, source_updated_at text) ON CONFLICT (board_id, item_id) DO UPDATE SET raw=EXCLUDED.raw, source_updated_at=EXCLUDED.source_updated_at, deleted_at=NULL, mirrored_at=NOW()`; await sql`UPDATE vybe_mirror_items SET deleted_at=NOW(), mirrored_at=NOW() WHERE board_id=${MIRROR_BOARD_ID} AND deleted_at IS NULL AND NOT EXISTS ( SELECT 1 FROM jsonb_to_recordset(${json(rows.map(row => ({ item_id: row.item_id })))}::jsonb) AS record(item_id text) WHERE record.item_id = vybe_mirror_items.item_id )`; } await setMeta(sql, `board:${MIRROR_BOARD_ID}:status_options`, statusOptions); await setMeta(sql, `board:${MIRROR_BOARD_ID}:last_bootstrap`, { at: new Date().toISOString(), count: items.length }); await sql`INSERT INTO vybe_mirror_changes (board_id, operation, raw) VALUES (${MIRROR_BOARD_ID}, 'bootstrap', ${json({ count: items.length })}::jsonb)`; return { count: items.length, version: await latestVersion(sql), status_options: statusOptions }; }
export async function reconcileMirror(reason = 'manual') { if (reconcilePromise) return reconcilePromise; reconcilePromise = (async () => { await ensureMirrorSchema(); const sql = database(); const key = `board:${MIRROR_BOARD_ID}:last_reconcile_request`; const existing = await sql`SELECT meta_value FROM vybe_mirror_meta WHERE meta_key=${key}`; const lastAt = Number(existing[0]?.meta_value?.at || 0); if (lastAt && Date.now() - lastAt < MIRROR_RECONCILE_MIN_INTERVAL_MS) { return { skipped: true, reason: 'recent_reconcile', version: await latestVersion(sql) }; } await setMeta(sql, key, { at: Date.now(), reason }); const result = await bootstrapMirror(); return { ...result, skipped: false, reason }; })().finally(() => { reconcilePromise = null; }); return reconcilePromise; }
export async function getMirrorSnapshot() { await ensureMirrorSchema(); const sql = database(); const [items, meta] = await Promise.all([ sql`SELECT raw FROM vybe_mirror_items WHERE board_id=${MIRROR_BOARD_ID} AND deleted_at IS NULL ORDER BY item_id`, sql`SELECT meta_key, meta_value, updated_at FROM vybe_mirror_meta WHERE meta_key IN (${`board:${MIRROR_BOARD_ID}:status_options`}, ${`board:${MIRROR_BOARD_ID}:last_bootstrap`})` ]); const values = Object.fromEntries(meta.map(row => [row.meta_key, row])); const statusMeta = values[`board:${MIRROR_BOARD_ID}:status_options`]?.meta_value || []; const bootstrapMeta = values[`board:${MIRROR_BOARD_ID}:last_bootstrap`]?.meta_value || null; return { ready: items.length > 0, board_id: MIRROR_BOARD_ID, version: await latestVersion(sql), items: items.map(row => row.raw), status_options: statusMeta, bootstrapped_at: bootstrapMeta?.at || null, source: 'vybe-operational-mirror' }; }
export async function getMirrorDelta(since = 0) { await ensureMirrorSchema(); const sql = database(); const version = await latestVersion(sql); const rows = await sql`SELECT change_id, item_id, operation, raw, source_updated_at, created_at FROM vybe_mirror_changes WHERE board_id=${MIRROR_BOARD_ID} AND change_id > ${Number(since) || 0} ORDER BY change_id ASC LIMIT 250`; const requiresSnapshot = rows.some(row => row.operation === 'bootstrap') || rows.length >= 250; return { version, requires_snapshot: requiresSnapshot, changes: requiresSnapshot ? [] : rows }; }
export async function registerEvent(event) { await ensureMirrorSchema(); const sql = database(); const uuid = String(event?.triggerUuid || event?.trigger_uuid || ''); if (!uuid) throw new Error('Evento sem triggerUuid.'); const inserted = await sql`INSERT INTO vybe_mirror_events (trigger_uuid, board_id, event_type, payload) VALUES (${uuid}, ${Number(event.boardId || MIRROR_BOARD_ID)}, ${String(event.type || '')}, ${json(event)}::jsonb) ON CONFLICT (trigger_uuid) DO NOTHING RETURNING trigger_uuid`; if (inserted.length) return { accepted: true, retry: false, trigger_uuid: uuid }; const existing = await sql`SELECT processed_at, processing_error FROM vybe_mirror_events WHERE trigger_uuid=${uuid}`; const prior = existing[0]; const retry = !!prior?.processing_error || !prior?.processed_at; return { accepted: retry, retry, trigger_uuid: uuid }; }
export async function mirrorItemFromEvent(event) { const boardId = Number(event?.boardId || MIRROR_BOARD_ID); if (boardId !== MIRROR_BOARD_ID) return { ignored: true, reason: 'board_not_managed' }; const itemId = String(event?.pulseId || event?.itemId || ''); if (!itemId) return { ignored: true, reason: 'item_not_present' }; const sql = database(); const eventType = String(event.type || '').toLowerCase(); const deleted = REMOVED_EVENT_TYPES.has(eventType) || eventType.includes('delete') || eventType.includes('archive'); const restored = RESTORED_EVENT_TYPES.has(eventType) || eventType.includes('restore') || eventType.includes('unarchive'); if (deleted && !restored) { await sql`UPDATE vybe_mirror_items SET deleted_at=NOW(), mirrored_at=NOW() WHERE board_id=${MIRROR_BOARD_ID} AND item_id=${itemId}`; await sql`INSERT INTO vybe_mirror_changes (board_id, item_id, operation, raw) VALUES (${MIRROR_BOARD_ID}, ${itemId}, 'delete', NULL)`; return { item_id: itemId, operation: 'delete' }; } const item = await fetchMondayItem(itemId); if (!item) return { ignored: true, reason: 'item_not_found' }; await sql`INSERT INTO vybe_mirror_items (board_id, item_id, raw, source_updated_at, deleted_at, mirrored_at) VALUES (${MIRROR_BOARD_ID}, ${itemId}, ${json(item)}::jsonb, ${String(item.updated_at || '')}, NULL, NOW()) ON CONFLICT (board_id, item_id) DO UPDATE SET raw=EXCLUDED.raw, source_updated_at=EXCLUDED.source_updated_at, deleted_at=NULL, mirrored_at=NOW()`; await sql`INSERT INTO vybe_mirror_changes (board_id, item_id, operation, raw, source_updated_at) VALUES (${MIRROR_BOARD_ID}, ${itemId}, 'upsert', ${json(item)}::jsonb, ${String(item.updated_at || '')})`; return { item_id: itemId, operation: 'upsert', item }; }
export async function markEventProcessed(triggerUuid, error = '') { await ensureMirrorSchema(); const sql = database(); const failed = !!error; await sql`UPDATE vybe_mirror_events SET processed_at=${failed ? null : new Date().toISOString()}, processing_error=${error || null} WHERE trigger_uuid=${String(triggerUuid)}`; }
export async function getMirrorHealth() { await ensureMirrorSchema(); const sql = database(); const [items, changes, events, meta] = await Promise.all([ sql`SELECT COUNT(*)::int AS count, MAX(mirrored_at) AS last_mirrored_at FROM vybe_mirror_items WHERE board_id=${MIRROR_BOARD_ID} AND deleted_at IS NULL`, sql`SELECT COUNT(*)::int AS count, MAX(created_at) AS last_change_at FROM vybe_mirror_changes WHERE board_id=${MIRROR_BOARD_ID}`, sql`SELECT COUNT(*)::int AS received, COUNT(processed_at)::int AS processed, COUNT(processing_error)::int AS errors, MAX(received_at) AS last_event_at FROM vybe_mirror_events WHERE board_id=${MIRROR_BOARD_ID}`, sql`SELECT meta_value, updated_at FROM vybe_mirror_meta WHERE meta_key=${`board:${MIRROR_BOARD_ID}:last_bootstrap`}` ]); return { board_id: MIRROR_BOARD_ID, version: await latestVersion(sql), items: items[0], changes: changes[0], events: events[0], bootstrap: meta[0] || null, generated_at: new Date().toISOString() }; }
